#ifndef CONFIG_H
#define CONFIG_H

#define MAPBASE_TILE_WIDTH 64
#define MAPBASE_TILE_HEIGHT 64
#define MAPBASE_TILE_COUNT MAPBASE_TILE_WIDTH * MAPBASE_TILE_HEIGHT
#define MAPBASE_SIZE MAPBASE_TILE_COUNT*2

#define L1_MAPBASE_TILE_WIDTH 64
#define L1_MAPBASE_TILE_HEIGHT 32
#define L1_MAPBASE_TILE_COUNT L1_MAPBASE_TILE_WIDTH * L1_MAPBASE_TILE_HEIGHT
#define L1_MAPBASE_SIZE L1_MAPBASE_TILE_COUNT*2

// Our default Tile and Map Base addresses
#define L0_MAPBASE_ADDR 0x00000L
#define L1_MAPBASE_ADDR L0_MAPBASE_ADDR + MAPBASE_SIZE 
#define TILEBASE_ADDR L1_MAPBASE_ADDR + L1_MAPBASE_SIZE

#define TILESET_FONT_INDEX 10
#define TILEBASE_FONT_START TILEBASE_ADDR + (TILESET_FONT_INDEX*256)
#define TILESET_COUNT 52
#define TILESET_SIZE 256*TILESET_COUNT

#define TANK_SPRITE_ANGLE_FRAMES 5

#define TANK_FRAME_SIZE 1024
#define SPRITE_GRAPHICS_ADDR TILEBASE_ADDR + TILESET_SIZE
#define TANK_A_SPRITE_GRAPHICS_ADDR SPRITE_GRAPHICS_ADDR
#define TANK_B_SPRITE_GRAPHICS_ADDR TANK_A_SPRITE_GRAPHICS_ADDR+(TANK_FRAME_SIZE*TANK_SPRITE_ANGLE_FRAMES)
#define TANK_C_SPRITE_GRAPHICS_ADDR TANK_B_SPRITE_GRAPHICS_ADDR+(TANK_FRAME_SIZE*TANK_SPRITE_ANGLE_FRAMES)

#define BALL_A_SPRITE_GRAPHICS_ADDR TILEBASE_ADDR + (4 * 256)
#define BALL_B_SPRITE_GRAPHICS_ADDR BALL_A_SPRITE_GRAPHICS_ADDR+256

#define PALETTE_ADDR 0x1FA00L

void init();
void setZoom(unsigned char zoomMode);
void clearLayers();
void clearLayer0();
void clearLayer1();
void pickModes(unsigned char *zoomMode, unsigned char *gameMode, unsigned char *courseCount);
void waitForButtonPress();

#endif